function clcres()
%CLCRES Clear all the result files generated by the c program
%   Clear out CSV files in 2 subfolders within the project directory: "MovieFrames/" and "Output/". 
%   This function checks which computer account is being used and then assign the project path accordingly. 
%
%   Keyboard input:: 
%       'Y' or 'YES':     Clear out all CSV files in those two folders. Input is NOT case-sensitive
%       Any other input:  Abort deletion. No files are changed
%

username = getenv('USER');  % Computer account user name
prompt = "\n  - Confirm to clear all c result files (Y/N): ";
if ismac && strcmp(username, 'chuckjia') % Macbook Pro
    projectPath = "~/Documents/Workspace/Git/Numerical-Repo/HumidityV3/";
    prompt = "On [Chuck's Macbook Pro] " + prompt;
elseif isunix && strcmp(username, 'chuck') % Office Ubuntu
    projectPath = "~/git/Numerical-Repo/HumidityV3/";
    prompt = "On [Chuck's Office Ubuntu] " + prompt;
else
    fprintf("Unknown computer!! Cannot perform delete operations.\n");
    return
end

act = lower(input(char(prompt), 's'));

if strcmp(act, 'y') || strcmp(act, 'yes')
    delete(projectPath + "MovieFrames/*.csv")
    delete(projectPath + "MovieFrames2/*.csv")
    delete(projectPath + "Output/*.csv")
    if exist(projectPath + "Output/out", 'file')
        delete(projectPath + "Output/out")
    end
    fprintf("All CSV and output files with in MovieFrames and Output cleared.\n");
    return
end

fprintf("Aborted: no file deleted.\n");

end

