% File list and titles

fileList = ["T_soln", "q_soln", "u_soln", "w_soln", ...
    "T_err", "q_err", "u_err", "w_err",...
    "T_exact", "q_exact", "u_exact", "w_exact" ];

graphTitleList = [
    "Numerical Solution: T", "Numerical Solution: q", ...
    "Numerical Solution: u", "Numerical Solution: w", ...
    "Error: T", "Error: q", "Error: u", "Error: w", ...
    "Exact Solution: T", "Exact Solution: q", ...
    "Exact Solution: u", "Exact Solution: w"];